import { Client } from 'pg';
import { IEntity } from "@loomcore/common/models";
import type { AppIdType } from "@loomcore/common/types";
import { BadRequestError, DuplicateKeyError } from "../../../errors/index.js";
import { columnsAndValuesFromEntity } from '../utils/columns-and-values-from-entity.js';

export async function create<T extends IEntity>(
    client: Client,
    pluralResourceName: string,
    entity: Partial<T>
): Promise<{ insertedId: AppIdType; entity: T }> {
    try {
        // Remove _id from entity - it will be auto-generated by the database
        delete entity._id;

        const { columns, values } = columnsAndValuesFromEntity(entity);
        
        // Build parameterized query
        const placeholders = columns.map((_, index) => `$${index + 1}`).join(', ');
        const query = `
            INSERT INTO "${pluralResourceName}" (${columns.join(', ')})
            VALUES (${placeholders})
            RETURNING *
        `;

        const result = await client.query<T>(query, values);
        if (result.rows.length === 0) {
            throw new BadRequestError(`Error creating ${pluralResourceName}: No row returned`);
        }
        
        // Get the actual database row with all converted values
        const insertedRow = result.rows[0];
        const insertedId = insertedRow._id as AppIdType;
        
        return {
            insertedId: insertedId,
            entity: insertedRow
        };
    }
    catch (err: any) {
        // PostgreSQL error code 23505 is for unique constraint violations
        if (err.code === '23505') {
            throw new DuplicateKeyError(`${pluralResourceName} already exists`);
        }
        throw new BadRequestError(`Error creating ${pluralResourceName}: ${err.message}`);
    }
}

